### ISSUE TITLE
CFF flavored fonts must be detected as valid WOFFs too

### ISSUE THREAD

**Issue by ul** [junmer/is-woff#1]
2nd word of WOFF header is its flavor, which could be either `0x00010000` or `0x4F54544F` [(details).](https://people.mozilla.org/~jkew/woff/woff-spec-latest.html) Package returns false negative in the second case.

**Comment by junmer** [comment]
thank you @ul , fixed 0ca92b97e50f2b1ef8b80212543efb811963ad55

**Comment by ul** [comment]
Thank you!
