### ISSUE TITLE
Latest release 1.0.2 is broken

### ISSUE THREAD

**Issue by plesiecki** [junmer/is-woff#2]
http://registry.npmjs.org/is-woff/-/is-woff-1.0.2.tgz misses index.js file :disappointed:

**Comment by junmer** [comment]
@plesiecki thank you fixed 1.0.3 f66b0846497788bbb6d8f78e2d07106919232089 :crying_cat_face: 
http://registry.npmjs.org/is-woff/-/is-woff-1.0.3.tgz 
 :sweat_smile:

**Comment by plesiecki** [comment]
:+1:
